### ISSUE TITLE
Picture Listing Issue IOS

### ISSUE THREAD

**Issue by Adnan-addi** [MohsinN/sellcast-issues#13]
Here i tried uploading 10 pictures , but when uploading bar shows i canceled it , and go back to picture or video selection screen and this time i select video and again filled the data in sellcast tab and for go for uploading , it still uploads 10 images but not the video i selected for upload.

**Comment by sarmadmakhdoom** [comment]
I think I have fixed, it, did not checked it on Simulator but please someone confirm that it is fixed
