### ISSUE TITLE
Listing Flow Images

### ISSUE THREAD

**Issue by sarmadmakhdoom** [MohsinN/sellcast-issues#15]
I think images in the flow are purely white, they have some alpha with them. In first screen text seems to be white but in Sale Type screen text is also greyed out a little. Please make it bright white without any alpha.

**Comment by Adnan-addi** [comment]
i need svg white icons , i will handle this issue .... Mohsin bhai , do send svg icons when you get free..

**Comment by Adnan-addi** [comment]
@sarmadmakhdoom thunmbnail selection pr jo horizontal images hen unko alpha dena hay ?

**Comment by sarmadmakhdoom** [comment]
@Adnan-addi jo unselected hein unko de dena, jo selected image hai wo normal rehe.
