### ISSUE TITLE
Stream Category Retained

### ISSUE THREAD

**Issue by sarmadmakhdoom** [MohsinN/sellcast-issues#19]
I selected a category and close the activity. Later when I create a new listing. it always shows my previously selected category. Like in the first run I tried Boats+RV+Motorcycles and in all further creations I see this category selected instead of Miscellaneous

**Comment by Adnan-addi** [comment]
category is fixed here by me , but title nd description still remains , no idea why fragment keep the data..?

**Comment by Adnan-addi** [comment]
fixed
