### ISSUE TITLE
Sellcast stream crashing when viewing.

### ISSUE THREAD

**Issue by bilalho2** [MohsinN/sellcast-issues#2]
View sellcast from other device user try to view and send offer.

**Comment by MohsinN** [comment]
Please explaing the issue or you can attach video here as well that you share on whatsapp.

**Comment by bilalho2** [comment]
Ok

On 12 Dec 2017 8:07 pm, "Mohsin" <notifications@github.com> wrote:

Please explaing the issue or you can attach video here as well that you
share on whatsapp.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MohsinN/sellcast-issues/issues/2#issuecomment-351078561>,
or mute the thread
