### ISSUE TITLE
Listing > BidCast

### ISSUE THREAD

**Issue by sarmadmakhdoom** [MohsinN/sellcast-issues#21]
In case of Listing > Pictures or Video > BidCast

Reserve Price and Listing Duration should be asked. Because we are not asking for another popup after listing is created in that case and once finished it should create the listing in the system with listClassificed end point so these two values should be asked in the listing process and at the end (after uploading media). It will list the item and show success popup.

Refer iOS flow

**Comment by sarmadmakhdoom** [comment]
Make sure that cars fragment should also have these new fields. Refer iOS again for explanation.

**Comment by Adnan-addi** [comment]
Added reserveprice option , and duration view in bidcast and carbid fragments , also attached to deobject , in case of live it doesnot ask for reserveprice option , and duration as it supposed to ask after finishing live stream .
