### ISSUE TITLE
FundCast Sale

### ISSUE THREAD

**Issue by sarmadmakhdoom** [MohsinN/sellcast-issues#27]
From Side menu FundCast listing still open the older flow. It need to be linked with the new flow and check labeling and descriptions are changed in the FundCast type of listings. Refer iOS

**Comment by MohsinN** [comment]
Fixed

**Comment by sarmadmakhdoom** [comment]
It souls created fundcast type of listing. Refer iOS flow

**Comment by sarmadmakhdoom** [comment]
Should*

**Comment by Adnan-addi** [comment]
fixed
